C NAME: SAGAR DAM; ROLL: PHYS010; REG: 16120917010
C PROGRAMME FOR SOLVING N SIMULTANEOUS LINEAR EQN FOR N UNKNOWNS
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION A(20,20), X(20)
      OPEN(2,FILE='OUP')
      WRITE(*,*)'ENTER THE NO OF UNKNOWNS: '
      READ(*,*)N
      WRITE(*,*)'ENTER THE MATRIX ELEMENTS FOR THE AUGMENTED MATRIX: '
      WRITE(*,*)'[IN MATRIX FORM]'

C TAKING THE MATRIX ELEMENTS:
      DO 10 I=1,N
      READ(*,*)(A(I,J),J=1,N+1)
10    CONTINUE

      WRITE(2,*)'THE AUGMENTED MATRIX IS: '
      DO 80 I=1,N
      WRITE(2,*)(A(I,J),J=1,N+1)
80    CONTINUE

C  ELIMINATION OF VARIABLES AND MAKING UPPER TRIANGULAR MATRIX
      DO 20 K=1,N
      DO 30 I=K+1,N
      U=A(I,K)/A(K,K)
      DO 40 J=K,N+1
      A(I,J)=A(I,J)-U*A(K,J)
40    CONTINUE
30    CONTINUE
20    CONTINUE

      WRITE(2,*)'THE UPPER TRIANGULAR FORM IS: '
      DO 50 I=1,N
      WRITE(*,*)(A(I,J),J=1,N+1)
      WRITE(2,*)(A(I,J),J=1,N+1)
50    CONTINUE

C     BACK SUBSTITUTION
      X(N)=A(N,N+1)/A(N,N)
      
      DO 60 K=N-1,1,-1
      S=0.D0
      DO 70 I= K+1,N
      S=S+A(K,I)*X(I)
70    CONTINUE
      X(K)=(A(K,N+1)-S)/A(K,K)
60    CONTINUE

C     THE RESULT: 
      WRITE(2,*)''
      WRITE(2,*)'THE SOLUTION IS: '
500   FORMAT(3X,A,1X,I4,A,F15.12)
      DO 90 I=1,N
      WRITE(*,500)'X(',I,')=  ',X(I)
      WRITE(2,500)'X(',I,')=  ',X(I)
90    CONTINUE
       
      STOP
      END


