C NAME SAGAR DAM; ROLL: SAGAR DAM; REG: 16120917010
C PROGRAMME FOR SOLUTION OF TRANSCENDENTAL EQN BY N-R MATHODE
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      OPEN(2,FILE='OUP')
      WRITE(2,*)'THE EQN IS:' 
      WRITE(2,*)'F(X)= EXP(X)-1-X-(X^2)/2-((X^3)*EXP(0.3X))/6 = 0'
      WRITE(2,*)'TABLE FOR FINDING SEED: '
     
C SHOWING THE TABULAR FORM:      
      DO 10 I=1,21
      Z=F(I-11.d0)
      WRITE(2,*)'THE FUNCTIONAL VALUE FOR X=',I-11,' IS: ',Z
      WRITE(*,*)'THE FUNCTIONAL VALUE FOR X=',I-11,' IS: ',Z
10    CONTINUE
      
      WRITE(*,*)'ENTER THE SEED POINT USING TABLE: '
C SOLUTION OF THE EQN:
      READ(*,*)X
      WRITE(*,*)'CHOOSEN SEED: ',X
      WRITE(2,*)'CHOOSEN SEED: ',X
      WRITE(2,*)''
120   FORMAT(A,10X,A,29X,A,27X,A)

      WRITE(2,120)'Etn','x(i)','x(i+1)','f(x(i+1))'
      DO 20 I=1,500
      Y=X-F(X)/DF(X)
      
30    FORMAT(I2,3X,F30.20,3X,F30.20,3X,F30.20)
      WRITE(*,*)I,X,Y,F(Y)
      WRITE(2,30)I,X,Y,F(Y)
      IF(F(Y).LE.0.0000009d0)GOTO 100
      X=Y
20    CONTINUE

100   WRITE(2,*)''
      WRITE(2,*)'THE SOLUTION (CORRECT UPTO 6TH DECIMAL):', Y
      WRITE(2,*)'WITH F(x)=',F(Y)
      WRITE(*,*)Y,F(Y)
      STOP
      END

      DOUBLE PRECISION FUNCTION F(X)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      F=DEXP(X)-1.D0-X-X**2/2.D0-X**3*DEXP(0.3D0*X)/6D0
      RETURN
      END

      DOUBLE PRECISION FUNCTION DF(X)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DF=DEXP(X)-1-X-DEXP(0.3D0*X)*(3*X**2+0.3D0*X**3)/6.D0
      RETURN
      END

